### PR TITLE
README.md Updated

### PR DESCRIPTION
**Pull request by vikasdfghjl**

### CODE REVIEW

**Comment by tausiq2003** [comment]
Hello vikash, Do you know md file design?

**Comment by vikasdfghjl** [comment]
These days I'm learning about the md files.
like what are these, how to create.

**Comment by vikasdfghjl** [comment]
so Yeah, I know about these

**Comment by tausiq2003** [comment]
Can you design the readme and raise a pr?

**Comment by vikasdfghjl** [comment]
Sure I would love to do it. Actually I have already raised this PR, to keep
adding the content. and Also I'll drop this repository link in my Server.

**Comment by tausiq2003** [comment]
Sure

**Comment by vikasdfghjl** [comment]
Cool, thanks!

**Comment by vikasdfghjl** [comment]
how do you want me to make this README.md file

**Comment by tausiq2003** [comment]
quite more design.

**Pull request closed without merging**
